version: '3.8'

services:
  vise-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vise-payment-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      # Para desarrollo, comentar esta línea en producción
      - ./public:/app/public:ro
    networks:
      - vise-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/stats"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M

networks:
  vise-network:
    driver: bridge
    name: vise-payment-network